### PR TITLE
Add Status setting

### PR DESCRIPTION
**Pull request by nerrixde**
Allow setting status

```py
mac.set_status_text("!help for commands")
```

### CODE REVIEW

**Comment by AmitGamingKing** [comment]
I used this now my status is my bot's phone number -_-

**Review by x-frst — COMMENTED** [review]
It is not working, whatever the ``mac.set_status_text()`` is but it is setting it's own jid only!

**Comment by Crypti-x** [comment]
@AmitGamingKing You're right.
I am banned so I was unable to test it. I need to close this PR.

**Comment by jesusvalverde** [comment]
def set_status_text(text, success=None, error=None):
    entity._sendIq(SetStatusIqProtocolEntity(text), success, error)
//over mac.py

the entity.getOwnJid() makes the Jid the status , just deleted.

Tested and working, can someelse make the modification over the branch.
@AmitGamingKing  or @Crypti-x

**Comment by AmitGamingKing** [comment]
Let's wait for @danielcardeenas to reply!

**Pull request closed without merging**
